// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Find the original in:
// https://github.com/GoogleCloudPlatform/golang-samples/blob/master/profiler/shakesapp/shakesapp/shakesapp.proto
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: shakesapp.proto

package shakesapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShakespeareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// match_count is the number of matching lines.
	MatchCount int64 `protobuf:"varint,1,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
}

func (x *ShakespeareResponse) Reset() {
	*x = ShakespeareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shakesapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShakespeareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShakespeareResponse) ProtoMessage() {}

func (x *ShakespeareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shakesapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShakespeareResponse.ProtoReflect.Descriptor instead.
func (*ShakespeareResponse) Descriptor() ([]byte, []int) {
	return file_shakesapp_proto_rawDescGZIP(), []int{0}
}

func (x *ShakespeareResponse) GetMatchCount() int64 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

type ShakespeareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// query is a substring query.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ShakespeareRequest) Reset() {
	*x = ShakespeareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shakesapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShakespeareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShakespeareRequest) ProtoMessage() {}

func (x *ShakespeareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shakesapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShakespeareRequest.ProtoReflect.Descriptor instead.
func (*ShakespeareRequest) Descriptor() ([]byte, []int) {
	return file_shakesapp_proto_rawDescGZIP(), []int{1}
}

func (x *ShakespeareRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_shakesapp_proto protoreflect.FileDescriptor

var file_shakesapp_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x61, 0x70, 0x70, 0x22, 0x36, 0x0a, 0x13,
	0x53, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x70, 0x65, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x70, 0x65,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x32, 0x66, 0x0a, 0x12, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x70, 0x65, 0x61, 0x72, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x73,
	0x61, 0x70, 0x70, 0x2e, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x70, 0x65, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x61,
	0x70, 0x70, 0x2e, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x73, 0x70, 0x65, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x73, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shakesapp_proto_rawDescOnce sync.Once
	file_shakesapp_proto_rawDescData = file_shakesapp_proto_rawDesc
)

func file_shakesapp_proto_rawDescGZIP() []byte {
	file_shakesapp_proto_rawDescOnce.Do(func() {
		file_shakesapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_shakesapp_proto_rawDescData)
	})
	return file_shakesapp_proto_rawDescData
}

var file_shakesapp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shakesapp_proto_goTypes = []interface{}{
	(*ShakespeareResponse)(nil), // 0: shakesapp.ShakespeareResponse
	(*ShakespeareRequest)(nil),  // 1: shakesapp.ShakespeareRequest
}
var file_shakesapp_proto_depIdxs = []int32{
	1, // 0: shakesapp.ShakespeareService.GetMatchCount:input_type -> shakesapp.ShakespeareRequest
	0, // 1: shakesapp.ShakespeareService.GetMatchCount:output_type -> shakesapp.ShakespeareResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shakesapp_proto_init() }
func file_shakesapp_proto_init() {
	if File_shakesapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shakesapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShakespeareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shakesapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShakespeareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shakesapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shakesapp_proto_goTypes,
		DependencyIndexes: file_shakesapp_proto_depIdxs,
		MessageInfos:      file_shakesapp_proto_msgTypes,
	}.Build()
	File_shakesapp_proto = out.File
	file_shakesapp_proto_rawDesc = nil
	file_shakesapp_proto_goTypes = nil
	file_shakesapp_proto_depIdxs = nil
}
